JOIN
O Pyspark Join é usado para combinar dois DataFrames e, encadeando-os, você pode juntar vários DataFrames;
Ele suporta todas as operações básicas de tipo de junção disponíveis no SQL tradicional, como INNER< LEFT OUTER, RIGHT OUTER, LEFT ANTI, LEFT SEMI, CROSS, SELF JOIN.

EXEMPLOS:


inner ==> INNER JOIN SQL
outer, full, fullouter, full_outer ==> FULL OUTER JOIN
left, leftouter, left_outer ==> LEFT JOIN
right, rightouter, right_outer ==> RIGHT JOIN
cross
anti, leftanti, left_anti
semi, leftsemi, left_semi

In [0]:
import pyspark.sql.functions as F

In [0]:
dados1 = [
         (1,"Anderson",1000.00),
         (2,"Kennedy",2000.00),
         (3,"Bruno",2300.00),
         (4,"Maria",2300.00),
         (5,"Eduardo",2400.00),
         (6,"Mendes",1900.00),
         (7,"Kethlyn",1500.00),
         (8,"Thiago",1800.00),
         (9,"Carla",2100.00)
]

schema = ["id","nome","salario"]

df1 = spark.createDataFrame(data=dados1,schema=schema)

df1.printSchema()
#df.show() ou
display(df1)

id,nome,salario
1,Anderson,1000.0
2,Kennedy,2000.0
3,Bruno,2300.0
4,Maria,2300.0
5,Eduardo,2400.0
6,Mendes,1900.0
7,Kethlyn,1500.0
8,Thiago,1800.0
9,Carla,2100.0

In [0]:
dados2 = [
    (1, "Delhi", "India"),
    (2, "Tamil Nadu", "India"),
    (3, "London", "UK"),
    (4, "Sydney", "Australia"),
    (8, "New York", "USA"),
    (9, "California", "USA"),
    (10, "New Jersey", "USA"),
    (11, "Texas", "USA"),
    (12, "Chicago", "USA")
]
schema2 = ["id", "local", "pais"]

df2 = spark.createDataFrame(data=dados2,schema=schema2)

df2.printSchema()

df2.display()

id,local,pais
1,Delhi,India
2,Tamil Nadu,India
3,London,UK
4,Sydney,Australia
8,New York,USA
9,California,USA
10,New Jersey,USA
11,Texas,USA
12,Chicago,USA

Verifica algum **campo em comum** nos dois dataframes, e retorna os resultados

novoDataFrame = dataframe1.**join**(dataframe2,**on=['coluna para comparar']**,how=*'inner'*)

In [0]:
df_inner = df1.join(df2, on=['id'],how='inner')
df_inner.display()

id,nome,salario,local,pais
1,Anderson,1000.0,Delhi,India
2,Kennedy,2000.0,Tamil Nadu,India
3,Bruno,2300.0,London,UK
4,Maria,2300.0,Sydney,Australia
8,Thiago,1800.0,New York,USA
9,Carla,2100.0,California,USA

Retorna todos os dados do DataFrame da coluna da esquerda e da direita

Junta todos os dados

Coloca null onde não há conexão entre os DataFrames

In [0]:
df_outer = df1.join(df2,on=['id'],how='outer')
df_outer.display()

id,nome,salario,local,pais
1,Anderson,1000.0,Delhi,India
2,Kennedy,2000.0,Tamil Nadu,India
3,Bruno,2300.0,London,UK
4,Maria,2300.0,Sydney,Australia
5,Eduardo,2400.0,null,null
6,Mendes,1900.0,null,null
7,Kethlyn,1500.0,null,null
8,Thiago,1800.0,New York,USA
9,Carla,2100.0,California,USA
10,null,null,New Jersey,USA
11,null,null,Texas,USA
12,null,null,Chicago,USA

Retorna todos os dados do DataFrame da coluna da esquerda e os registros que fazem "match"

Onde não tiver conexão com o DataFrame esquerdo, ele coloca null automaticamente

In [0]:
df_left = df1.join(df2,on=['id'],how='left')
df_left.display()

id,nome,salario,local,pais
1,Anderson,1000.0,Delhi,India
2,Kennedy,2000.0,Tamil Nadu,India
3,Bruno,2300.0,London,UK
4,Maria,2300.0,Sydney,Australia
5,Eduardo,2400.0,null,null
6,Mendes,1900.0,null,null
7,Kethlyn,1500.0,null,null
8,Thiago,1800.0,New York,USA
9,Carla,2100.0,California,USA

Retorna todos os dados do DataFrame da coluna da Direita e os registros que fazem "match"

Onde não tiver conexão com o DataFrame esquerdo, ele coloca null automaticamente

In [0]:
df_right = df1.join(df2,on=['id'],how='right')
df_right.display()

id,nome,salario,local,pais
1,Anderson,1000.0,Delhi,India
2,Kennedy,2000.0,Tamil Nadu,India
3,Bruno,2300.0,London,UK
4,Maria,2300.0,Sydney,Australia
8,Thiago,1800.0,New York,USA
9,Carla,2100.0,California,USA
10,null,null,New Jersey,USA
11,null,null,Texas,USA
12,null,null,Chicago,USA

Retorna todos os dados do DataFrame da Esquerda que não estão presentes no DataFrame da Direita

In [0]:
df_left_anti = df1.join(df2,on=['id'],how='left_anti')
df_left_anti.display()

id,nome,salario
5,Eduardo,2400.0
6,Mendes,1900.0
7,Kethlyn,1500.0

Retorna todos os dados do DataFrame da Esquerda que possuam correspondencia com o DataFrame da direita

Parecido com o INNER JOIN, porém so retorna os dados da DataFrame da esquerda, ao invés dos dados de ambos

In [0]:
df_left_semi = df1.join(df2,on=['id'],how='left_semi')
df_left_semi.display()

id,nome,salario
1,Anderson,1000.0
2,Kennedy,2000.0
3,Bruno,2300.0
4,Maria,2300.0
8,Thiago,1800.0
9,Carla,2100.0

Igual ao Outer Join

Retorna todos os dados do DataFrame da coluna da esquerda e da direita

Junta todos os dados

Coloca null onde não há conexão entre os DataFrames

In [0]:
df_full = df1.join(df2,on=['id'],how='full')
df_full.display()

id,nome,salario,local,pais
1,Anderson,1000.0,Delhi,India
2,Kennedy,2000.0,Tamil Nadu,India
3,Bruno,2300.0,London,UK
4,Maria,2300.0,Sydney,Australia
5,Eduardo,2400.0,null,null
6,Mendes,1900.0,null,null
7,Kethlyn,1500.0,null,null
8,Thiago,1800.0,New York,USA
9,Carla,2100.0,California,USA
10,null,null,New Jersey,USA
11,null,null,Texas,USA
12,null,null,Chicago,USA

In [0]:
Retorna todos os elementos do DataFrame da Esquerda que não possuem nenhuma correspondencia com o DataFrame da Direita

Igual ao Left Anti

In [0]:
df_anti = df1.join(df2,on=['id'],how='anti')
df_anti.display()

id,nome,salario
5,Eduardo,2400.0
6,Mendes,1900.0
7,Kethlyn,1500.0